name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Plan
        run: |
          cd /home/hiba/cloud-autoheal/terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd /home/hiba/cloud-autoheal/terraform
          terraform apply -auto-approve
